### ISSUE TITLE
Can you add Marathi language to the list of languages?

### ISSUE THREAD

**Issue by sharan165** [sanskrit/sanskrit#7]
Marathi language seems to be the only one missing from the list here, it would be great if you add it in the near future.

**Comment by drdhaval2785** [comment]
Are you talking about transliteration?

Transliteration is based on scripts and not language.
Devanagari scipt is already there. 
So, Hindi / Sanskrit / Marathi or any other language which uses Devanagari script is anyhow covered.

**Comment by sharan165** [comment]
@drdhaval2785 

Thanks for the reply, I tried using indic-transliteration but I got an output with letter 'B'' in the beginning.

Can you please have a look and help me on this?



    import codecs,string
    from indic_transliteration import sanscript
    from indic_transliteration.sanscript import SchemeMap, SCHEMES, transliterate

    def is_hindi(character):
        maxchar = max(character)
        if u'\u0900' <= maxchar <= u'\u097f':
            return character
        else:
            print(transliterate(character, sanscript.ITRANS, sanscript.DEVANAGARI)) 

    character = 'Bakrya vikne ahe'
    is_hindi(character)

    Output:

    Bअक्र्य विक्ने अहे

**Comment by drdhaval2785** [comment]
What does 'B' stand for in ITRANS? What did you expect the outcome to be?

bakrya बक्र्य
bhakrya - भक्र्य
B does not have any meaning in ITRANS as far as I know.

**Comment by sharan165** [comment]
@drdhaval2785 Yess the 1st option is what I am looking for!
